"""Glossary definitions and hover-help helpers."""

from __future__ import annotations

import html


GLOSSARY: dict[str, str] = {
    "Ticker": "The exchange symbol used to identify a stock, such as AAPL or NVDA.",
    "OHLCV": "Open, High, Low, Close, and Volume price data for each trading period.",
    "Close": "The final traded price for the selected period.",
    "Volume": "Number of shares traded during a period.",
    "Market Cap": "Market capitalization: share price multiplied by shares outstanding.",
    "MA20": "20-day moving average, used as a short-term trend measure.",
    "MA50": "50-day moving average, used as a medium-term trend measure.",
    "MA200": "200-day moving average, often used as a long-term trend measure.",
    "RSI": "Relative Strength Index, a 0-100 momentum indicator. Above 70 is often considered overheated; below 30 is often considered oversold.",
    "Annualized Volatility": "A yearly estimate of price variability based on daily returns.",
    "Volatility": "A measure of how much a stock price fluctuates. In this project, volatility is annualized from daily returns.",
    "Max Drawdown": "The largest peak-to-trough decline over the selected period.",
    "Revenue": "Total sales generated by the company.",
    "Revenue Growth YoY": "Year-over-year revenue growth.",
    "Revenue Growth": "How much company revenue increased or decreased over a period. In this project, the dashboard usually shows year-over-year revenue growth.",
    "Net Income Growth YoY": "Year-over-year growth in net income.",
    "Revenue CAGR": "Compound annual growth rate of revenue over multiple years.",
    "Gross Margin": "Gross profit divided by revenue.",
    "Operating Margin": "Operating income divided by revenue.",
    "Net Margin": "Net income divided by revenue.",
    "Free Cash Flow": "Operating cash flow minus capital expenditures.",
    "FCF Margin": "Free cash flow divided by revenue.",
    "ROE": "Return on equity: net income divided by shareholders' equity.",
    "ROA": "Return on assets: net income divided by total assets.",
    "ROIC": "Return on invested capital, a simplified operating return on debt plus equity capital.",
    "Debt-to-Equity": "Total debt divided by shareholders' equity.",
    "Current Ratio": "Current assets divided by current liabilities.",
    "Interest Coverage": "Operating income divided by interest expense.",
    "TTM": "Trailing twelve months; recent annualized financial performance.",
    "P/E": "Price-to-earnings valuation. In this project, target price equals forward EPS multiplied by a P/E multiple.",
    "P/S": "Price-to-sales valuation. In this project, forward revenue is multiplied by a P/S multiple and divided by shares outstanding.",
    "DCF": "Discounted cash flow valuation based on future free cash flow assumptions.",
    "Forward EPS": "Expected future earnings per share.",
    "Forward Revenue": "Expected future revenue.",
    "Shares Outstanding": "Number of company shares used to convert equity value into price per share.",
    "Base Free Cash Flow": "Starting free cash flow input for the DCF model.",
    "Growth Rate": "Assumed annual free cash flow growth during the DCF projection period.",
    "Discount Rate": "Rate used to discount future cash flows back to present value.",
    "Terminal Growth Rate": "Long-term growth assumption used after the explicit DCF forecast period.",
    "Terminal Value": "Estimated company value after the explicit forecast period in a DCF model.",
    "Enterprise Value": "Value of the operating business before subtracting net debt.",
    "Equity Value": "Enterprise value minus net debt.",
    "Net Debt": "Debt minus cash and equivalents.",
    "Bear": "Pessimistic scenario assumption set.",
    "Base": "Middle-case scenario assumption set.",
    "Bull": "Optimistic scenario assumption set.",
}


def term_help(term: str) -> str:
    """Return tooltip text for a glossary term."""

    return GLOSSARY.get(term, "Term explanation is not available yet.")


def abbr(term: str) -> str:
    """Return an HTML abbreviation element with hover text."""

    escaped_term = html.escape(term)
    escaped_description = html.escape(term_help(term), quote=True)
    return f'<abbr title="{escaped_description}">{escaped_term}</abbr>'
